id: AE6DD8C6E
title: Aspiration Written in Sadness During the Water Snake Year
type: translation
pechas:
- IF61DB2A9
- ID3D2CE8A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:06:23.566878
  last_modified_at: 2023-01-04 12:06:23.566892
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  IF61DB2A9/758C: 51AB
  ID3D2CE8A/D477: 51AB
